import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from './providers';

const inter = Inter({ subsets: ["latin"] });

/* Fonts Kode */
const kodeMonoRegular = localFont({
  src: "./fonts/kode/KodeMono-Regular.ttf",
  variable: '--font-kode-regular-mono',
  weight: '400',
});
const kodeMonoMedium = localFont({
  src: "./fonts/kode/KodeMono-Medium.ttf",
  variable: '--font-kode-medium-mono',
  weight: '500',
});
const kodeMonoSemiBold = localFont({
  src: "./fonts/kode/KodeMono-SemiBold.ttf",
  variable: '--font-kode-semi-bold-mono',
  weight: '600',
});
const kodeMonoBold = localFont({
  src: "./fonts/kode/KodeMono-Bold.ttf",
  variable: '--font-kode-bold-mono',
  weight: '700',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${kodeMonoRegular.variable} ${kodeMonoMedium.variable} ${kodeMonoSemiBold.variable} ${kodeMonoBold.variable } antialiased` }>
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}

