import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/* Fonts Kode */
/* const kodeMonoRegular = localFont({
  src: "./fonts/kode/KodeMono-Regular.ttf",
  variable: '--font-kode-regular-mono',
  weight: '400',
});

const kodeMonoMedium = localFont({
  src: "./fonts/kode/KodeMono-Medium.ttf",
  variable: '--font-kode-medium-mono',
  weight: '500',
});

const kodeMonoSemiBold = localFont({
  src: "./fonts/kode/KodeMono-SemiBold.ttf",
  variable: '--font-kode-semi-bold-mono',
  weight: '600',
});

const kodeMonoBold = localFont({
  src: "./fonts/kode/KodeMono-Bold.ttf",
  variable: '--font-kode-bold-mono',
  weight: '700',
}) */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className }>
        {children}
      </body>
      
    </html>
  );
}

